version: "3.9"

services:
  voteapp-redis:
    image: redis:latest
    container_name: voteapp-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  voteapp-postgres:
    image: postgres:15-alpine
    container_name: voteapp-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  voteapp-vote:
    build:
      context: ./vote
    container_name: voteapp-vote
    depends_on:
      - voteapp-redis
      - voteapp-postgres
    env_file: .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - OPTION_A=${OPTION_A}
      - OPTION_B=${OPTION_B}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend

  voteapp-worker:
    build:
      context: ./worker
    container_name: voteapp-worker
    depends_on:
      - voteapp-redis
      - voteapp-postgres
    env_file: .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: unless-stopped
    networks:
      - backend

  voteapp-result:
    build:
      context: ./result
    container_name: voteapp-result
    depends_on:
      - voteapp-postgres
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - OPTION_A=${OPTION_A}
      - OPTION_B=${OPTION_B}
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
